### ISSUE TITLE
widget.py - TypeError: can't convert float to int

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_DisplayIO_Layout#66]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=47&t=186239

Added a dump of the values just before this line:
https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/blob/48b512a391732c03aff8556a0a2d688777e672a9/adafruit_displayio_layout/widgets/widget.py#L230
thusly:
```python
print(self._anchored_position[0], self._anchor_point[0], self._bounding_box[2], self._bounding_box[0])
```
and get:
```python
6.0 0.0 93 0
```

So some of the values are float making the result also float. `displayio.Group.x` requires `int`.

**Comment by FoamyGuy** [comment]
Interesting. I'm not sure why it was able to run successfully in the past. 

`anchored_position` should generally be a tuple of ints since it represents a pixel location on the display. There are several places where the double divided by `//` operator is used convert the results of dividing to an int. Maybe there one or more spots where I missed that and it's dividing with `/` 

No matter how it got the float into `anchored_position` though the Widget should handle it more gracefully. I think we can convert to int here before setting the value of `x` and `y` properties on the Group instance. https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/blob/48b512a391732c03aff8556a0a2d688777e672a9/adafruit_displayio_layout/widgets/widget.py#L231-L240

I can look into this more and make a PR for it tonight. There is a similar (but not exact same) issue resolved by one of the current PRs so I'll check that out tonight as well.

**Comment by caternuson** [comment]
I did a quick test of simply adding a final int cast in the assignment:
```python
self.x = int(
```
and same for `self.y`, and it fixed it.

But if this indicating an issue somewhere else, then might not be best fix.

**Comment by FoamyGuy** [comment]
Off the top of my head I think it indicates a possible bug in the Touch Deck code. But if that does exist I'm not sure why it would have ever run in the past, so possibly there is nothing needing fixing in there after all.

I do think adding the int cast like you did is a good solution. Even if there is a bug elsewhere causing float values to get set to the `anchored_position` I think Widget should handle it more gracefully. Someone could do something like:
```
widget.anchor_point = (0.5, 0.5)
widget.anchored_position = (180.0, 140.0)
```
And I think we should not crash in that case ideally, which the `int` cast should allow us to avoid.
